pipeline {
  agent {
    docker { image 'node:latest' }
  }
  stages {

    stage('Where we are') {
        steps { 
            sh 'echo "Working on path $(pwd)"' 
            sh 'echo "List of files $(ls -ltr)"' 
        }
    }

  }
}